trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build'

# (Optional) Cache dependencies to speed up builds
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    path: $(npm_config_cache)
  displayName: 'Cache npm dependencies'

# (Optional) Publish build artifacts for deployment
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'build'
    artifactName: 'react-build'
  displayName: 'Publish Build Artifacts'
